'use strict';

const Database = require('better-sqlite3');
const path = require('path');

const DB_PATH = process.env.DB_PATH
  ? path.resolve(process.env.DB_PATH)
  : path.join(__dirname, '..', 'crm.db');

const db = new Database(DB_PATH);
db.pragma('journal_mode = WAL');

// ── Idempotency guard ──────────────────────────────────────────────────────────
const existing = db.prepare("SELECT COUNT(*) AS cnt FROM applications WHERE id LIKE 'SEED-%'").get();
if (existing.cnt > 0) {
  console.log('Seed data already present — skipping.');
  db.close();
  process.exit(0);
}

// ── Sample applications (one per status) ──────────────────────────────────────
const now = new Date().toISOString();

const applications = [
  {
    id: 'SEED-001',
    companyName: 'Meridian Pay Technologies LLC',
    legalName: 'Meridian Pay Technologies LLC',
    trade_name: 'MeridianPay',
    businessType: 'LLC',
    entity_type: 'Limited Liability Company',
    ein: '47-2831940',
    country_of_incorporation: 'US',
    state_of_incorporation: 'Delaware',
    date_of_incorporation: '2019-03-15',
    business_registration_number: 'DE-LLC-2019-483921',
    naics_code: '522320',
    industry: 'Financial Technology',
    business_purpose: 'B2B payment processing and disbursement platform for marketplace operators.',
    website_url: 'https://www.meridianpay.io',
    website: 'https://www.meridianpay.io',
    mailing_address_street: '1250 Avenue of the Americas, Suite 2100',
    mailing_address_city: 'New York',
    mailing_address_state: 'NY',
    mailing_address_postal: '10020',
    mailing_address_country: 'US',
    primaryContactFirstName: 'Rachel',
    primaryContactLastName: 'Okonkwo',
    primaryContactEmail: 'r.okonkwo@meridianpay.io',
    primaryContactPhone: '+1-212-555-0182',
    primaryContactTitle: 'Chief Financial Officer',
    accountTypes: JSON.stringify(['operating', 'settlement']),
    account_type_operating: 1,
    account_type_settlement: 1,
    account_type_reserve: 0,
    requestedServices: JSON.stringify(['ach', 'wire', 'virtual_accounts', 'fraud_monitoring']),
    virtual_accounts_required: 1,
    intended_use: 'Marketplace escrow, merchant settlement, and disbursement to sub-merchants.',
    source_of_funds: 'Merchant transaction revenue and equity capital.',
    monthlyTransactionVolume: 12500000,
    estimated_monthly_dollar_volume: 12500000,
    expected_monthly_transaction_count: 45000,
    average_transaction_amount: 278,
    expected_average_balance: 3200000,
    internationalTransactions: 1,
    countries_customers_located: 'US, CA, GB',
    states_customers_located: 'NY, CA, TX, FL, IL',
    customer_types: 'SMB merchants, gig economy platforms',
    high_risk_jurisdictions: 0,
    sanctioned_countries_involvement: 0,
    ofac_screening_responsibility: 'Internal compliance team with Dow Jones Watchlist integration.',
    bsa_aml_attestation: 1,
    compliance_officer_name: 'Daniel Marsh',
    compliance_officer_contact: 'd.marsh@meridianpay.io',
    compliance_controls_description: 'Full BSA/AML program with automated transaction monitoring, CIP/KYC procedures, and SAR filing protocol.',
    training_program_available: 1,
    customers_migrating: 'Migrating 320 merchants from Stripe Treasury.',
    transition_plan_available: 1,
    accuracy_attestation: 1,
    electronic_signature: 'Rachel Okonkwo',
    signature_date: '2026-01-14',
    monthlyRevenue: 875000,
    employeeCount: 48,
    yearFounded: 2019,
    incorporationState: 'DE',
    form_step_completed: 3,
    status: 'submitted',
    assignedTo: 'Priya Nair',
    submittedAt: '2026-01-14T10:22:00.000Z',
    updatedAt: now,
    notes: 'Complete application received. Awaiting initial compliance review.',
  },
  {
    id: 'SEED-002',
    companyName: 'Apex Lending Partners Inc.',
    legalName: 'Apex Lending Partners Inc.',
    trade_name: 'ApexLend',
    businessType: 'Corporation',
    entity_type: 'C-Corporation',
    ein: '82-1049372',
    country_of_incorporation: 'US',
    state_of_incorporation: 'California',
    date_of_incorporation: '2016-07-22',
    business_registration_number: 'CA-CORP-2016-091847',
    naics_code: '522291',
    industry: 'Consumer Lending',
    business_purpose: 'Consumer installment lending and loan servicing platform.',
    website_url: 'https://www.apexlend.com',
    website: 'https://www.apexlend.com',
    mailing_address_street: '500 Sansome Street, Suite 450',
    mailing_address_city: 'San Francisco',
    mailing_address_state: 'CA',
    mailing_address_postal: '94111',
    mailing_address_country: 'US',
    primaryContactFirstName: 'Marcus',
    primaryContactLastName: 'Vega',
    primaryContactEmail: 'm.vega@apexlend.com',
    primaryContactPhone: '+1-415-555-0247',
    primaryContactTitle: 'VP of Banking Relations',
    accountTypes: JSON.stringify(['operating', 'reserve']),
    account_type_operating: 1,
    account_type_settlement: 0,
    account_type_reserve: 1,
    requestedServices: JSON.stringify(['ach', 'reconciliation_api']),
    virtual_accounts_required: 0,
    intended_use: 'Loan origination funding, repayment collection, and reserve management.',
    source_of_funds: 'Institutional debt capital and retained earnings.',
    monthlyTransactionVolume: 28000000,
    estimated_monthly_dollar_volume: 28000000,
    expected_monthly_transaction_count: 18000,
    average_transaction_amount: 1556,
    expected_average_balance: 8500000,
    internationalTransactions: 0,
    countries_customers_located: 'US',
    states_customers_located: 'CA, TX, AZ, NV, WA',
    customer_types: 'Individual consumers, credit-qualified borrowers',
    high_risk_jurisdictions: 0,
    sanctioned_countries_involvement: 0,
    ofac_screening_responsibility: 'Third-party vendor Socure handles OFAC screening at origination.',
    bsa_aml_attestation: 1,
    compliance_officer_name: 'Sandra Liu',
    compliance_officer_contact: 's.liu@apexlend.com',
    compliance_controls_description: 'State-licensed lender with full AML program, automated monitoring via Alloy, and quarterly BSA training.',
    training_program_available: 1,
    customers_migrating: null,
    transition_plan_available: 0,
    accuracy_attestation: 1,
    electronic_signature: 'Marcus Vega',
    signature_date: '2026-01-21',
    monthlyRevenue: 2100000,
    employeeCount: 112,
    yearFounded: 2016,
    incorporationState: 'CA',
    form_step_completed: 3,
    status: 'compliance_review',
    assignedTo: 'James Okafor',
    submittedAt: '2026-01-21T14:05:00.000Z',
    updatedAt: now,
    notes: 'Compliance team reviewing BSA/AML documentation. Requested state lending licenses.',
  },
  {
    id: 'SEED-003',
    companyName: 'Northgate Payroll Solutions LLC',
    legalName: 'Northgate Payroll Solutions LLC',
    trade_name: 'Northgate Payroll',
    businessType: 'LLC',
    entity_type: 'Limited Liability Company',
    ein: '35-7720184',
    country_of_incorporation: 'US',
    state_of_incorporation: 'Illinois',
    date_of_incorporation: '2018-11-03',
    business_registration_number: 'IL-LLC-2018-774320',
    naics_code: '541214',
    industry: 'Payroll Processing',
    business_purpose: 'Employer payroll processing, tax withholding, and direct deposit disbursement.',
    website_url: 'https://www.northgatepayroll.com',
    website: 'https://www.northgatepayroll.com',
    mailing_address_street: '200 W. Adams Street, Suite 1800',
    mailing_address_city: 'Chicago',
    mailing_address_state: 'IL',
    mailing_address_postal: '60606',
    mailing_address_country: 'US',
    primaryContactFirstName: 'Jennifer',
    primaryContactLastName: 'Stafford',
    primaryContactEmail: 'j.stafford@northgatepayroll.com',
    primaryContactPhone: '+1-312-555-0391',
    primaryContactTitle: 'Chief Operating Officer',
    accountTypes: JSON.stringify(['operating']),
    account_type_operating: 1,
    account_type_settlement: 0,
    account_type_reserve: 0,
    requestedServices: JSON.stringify(['ach', 'wire']),
    virtual_accounts_required: 0,
    intended_use: 'Employer payroll funding and employee direct deposit.',
    source_of_funds: 'Employer payroll deposits collected 2 days prior to payday.',
    monthlyTransactionVolume: 6200000,
    estimated_monthly_dollar_volume: 6200000,
    expected_monthly_transaction_count: 9500,
    average_transaction_amount: 653,
    expected_average_balance: 1800000,
    internationalTransactions: 0,
    countries_customers_located: 'US',
    states_customers_located: 'IL, WI, IN, MO, MN',
    customer_types: 'Small and mid-size employers, staffing agencies',
    high_risk_jurisdictions: 0,
    sanctioned_countries_involvement: 0,
    ofac_screening_responsibility: 'Internal HR compliance team with annual OFAC list refresh.',
    bsa_aml_attestation: 1,
    compliance_officer_name: 'Thomas Reyes',
    compliance_officer_contact: 't.reyes@northgatepayroll.com',
    compliance_controls_description: 'Employer verification at onboarding, payroll reconciliation controls, and annual BSA training for all staff.',
    training_program_available: 1,
    customers_migrating: null,
    transition_plan_available: 0,
    accuracy_attestation: 1,
    electronic_signature: 'Jennifer Stafford',
    signature_date: '2025-12-10',
    monthlyRevenue: 420000,
    employeeCount: 31,
    yearFounded: 2018,
    incorporationState: 'IL',
    form_step_completed: 3,
    status: 'action_required',
    assignedTo: 'Priya Nair',
    submittedAt: '2025-12-10T09:45:00.000Z',
    updatedAt: now,
    notes: 'IRS EIN verification letter outstanding. Requested updated Certificate of Good Standing for Illinois.',
  },
  {
    id: 'SEED-004',
    companyName: 'Clearbrook Insurance Payments Corp.',
    legalName: 'Clearbrook Insurance Payments Corp.',
    trade_name: 'Clearbrook Pay',
    businessType: 'Corporation',
    entity_type: 'C-Corporation',
    ein: '61-4398275',
    country_of_incorporation: 'US',
    state_of_incorporation: 'Texas',
    date_of_incorporation: '2014-02-28',
    business_registration_number: 'TX-CORP-2014-209384',
    naics_code: '524298',
    industry: 'Insurance Premium Finance',
    business_purpose: 'Insurance premium payment processing and remittance to carriers.',
    website_url: 'https://www.clearbrookpay.com',
    website: 'https://www.clearbrookpay.com',
    mailing_address_street: '2001 Ross Avenue, Suite 3200',
    mailing_address_city: 'Dallas',
    mailing_address_state: 'TX',
    mailing_address_postal: '75201',
    mailing_address_country: 'US',
    primaryContactFirstName: 'Andrea',
    primaryContactLastName: 'Whitfield',
    primaryContactEmail: 'a.whitfield@clearbrookpay.com',
    primaryContactPhone: '+1-214-555-0428',
    primaryContactTitle: 'President',
    accountTypes: JSON.stringify(['operating', 'settlement']),
    account_type_operating: 1,
    account_type_settlement: 1,
    account_type_reserve: 0,
    requestedServices: JSON.stringify(['ach', 'wire', 'reconciliation_api']),
    virtual_accounts_required: 0,
    intended_use: 'Collection of insurance premiums from policyholders and remittance to carrier trust accounts.',
    source_of_funds: 'Policyholder premium payments via ACH debit.',
    monthlyTransactionVolume: 18700000,
    estimated_monthly_dollar_volume: 18700000,
    expected_monthly_transaction_count: 31000,
    average_transaction_amount: 603,
    expected_average_balance: 4100000,
    internationalTransactions: 0,
    countries_customers_located: 'US',
    states_customers_located: 'TX, OK, LA, AR, NM',
    customer_types: 'Individual policyholders, small business owners',
    high_risk_jurisdictions: 0,
    sanctioned_countries_involvement: 0,
    ofac_screening_responsibility: 'Partnered carrier handles OFAC screening; Clearbrook performs secondary check at account opening.',
    bsa_aml_attestation: 1,
    compliance_officer_name: 'Brian Caldwell',
    compliance_officer_contact: 'b.caldwell@clearbrookpay.com',
    compliance_controls_description: 'State-regulated premium finance company. Annual independent BSA/AML audit. Transaction monitoring via Verafin.',
    training_program_available: 1,
    customers_migrating: null,
    transition_plan_available: 0,
    accuracy_attestation: 1,
    electronic_signature: 'Andrea Whitfield',
    signature_date: '2025-11-05',
    monthlyRevenue: 980000,
    employeeCount: 67,
    yearFounded: 2014,
    incorporationState: 'TX',
    form_step_completed: 3,
    status: 'approved',
    assignedTo: 'James Okafor',
    submittedAt: '2025-11-05T11:30:00.000Z',
    updatedAt: now,
    notes: 'Approved following full KYB review and BSA/AML officer interview. Sponsor bank agreement executed.',
  },
  {
    id: 'SEED-005',
    companyName: 'Vanta Embedded Finance Inc.',
    legalName: 'Vanta Embedded Finance Inc.',
    trade_name: 'VantaFi',
    businessType: 'Corporation',
    entity_type: 'C-Corporation',
    ein: '90-1284736',
    country_of_incorporation: 'US',
    state_of_incorporation: 'Delaware',
    date_of_incorporation: '2020-09-01',
    business_registration_number: 'DE-CORP-2020-827461',
    naics_code: '522390',
    industry: 'Embedded Finance / BaaS',
    business_purpose: 'Embedded banking infrastructure for SaaS platforms — accounts, cards, and payments as a service.',
    website_url: 'https://www.vantafi.com',
    website: 'https://www.vantafi.com',
    mailing_address_street: '340 Pine Street, Suite 700',
    mailing_address_city: 'San Francisco',
    mailing_address_state: 'CA',
    mailing_address_postal: '94104',
    mailing_address_country: 'US',
    primaryContactFirstName: 'Kwame',
    primaryContactLastName: 'Asante',
    primaryContactEmail: 'k.asante@vantafi.com',
    primaryContactPhone: '+1-415-555-0774',
    primaryContactTitle: 'Co-Founder & CEO',
    accountTypes: JSON.stringify(['operating', 'settlement', 'reserve']),
    account_type_operating: 1,
    account_type_settlement: 1,
    account_type_reserve: 1,
    requestedServices: JSON.stringify(['ach', 'wire', 'card_issuing', 'virtual_accounts', 'fraud_monitoring', 'reconciliation_api']),
    virtual_accounts_required: 1,
    intended_use: 'Operating account for own expenses; settlement accounts for end-client funds; reserve for chargebacks.',
    source_of_funds: 'Platform subscription revenue and Series B venture capital.',
    monthlyTransactionVolume: 55000000,
    estimated_monthly_dollar_volume: 55000000,
    expected_monthly_transaction_count: 210000,
    average_transaction_amount: 262,
    expected_average_balance: 12000000,
    internationalTransactions: 1,
    countries_customers_located: 'US, CA, GB, AU',
    states_customers_located: 'CA, NY, TX, WA, MA, CO',
    customer_types: 'SaaS platforms, vertical software companies, independent software vendors',
    high_risk_jurisdictions: 0,
    sanctioned_countries_involvement: 0,
    ofac_screening_responsibility: 'Automated OFAC screening on all end-users at onboarding and nightly batch via Persona.',
    bsa_aml_attestation: 1,
    compliance_officer_name: 'Fatima Al-Hassan',
    compliance_officer_contact: 'f.alhassan@vantafi.com',
    compliance_controls_description: 'Enterprise-grade BSA/AML program covering own operations and downstream platform customers. Real-time transaction monitoring, automated SAR workflow, and quarterly third-party audit.',
    training_program_available: 1,
    customers_migrating: 'Migrating 12 platform clients from Column Bank.',
    transition_plan_available: 1,
    accuracy_attestation: 1,
    electronic_signature: 'Kwame Asante',
    signature_date: '2025-09-18',
    monthlyRevenue: 3800000,
    employeeCount: 94,
    yearFounded: 2020,
    incorporationState: 'DE',
    form_step_completed: 3,
    status: 'live',
    assignedTo: 'James Okafor',
    submittedAt: '2025-09-18T16:00:00.000Z',
    updatedAt: now,
    notes: 'Live since November 2025. Quarterly review scheduled for Q1 2026.',
  },
  {
    id: 'SEED-006',
    companyName: 'Harbor Freight Factors LLC',
    legalName: 'Harbor Freight Factors LLC',
    trade_name: 'Harbor Factors',
    businessType: 'LLC',
    entity_type: 'Limited Liability Company',
    ein: '27-8830492',
    country_of_incorporation: 'US',
    state_of_incorporation: 'Florida',
    date_of_incorporation: '2022-04-10',
    business_registration_number: 'FL-LLC-2022-338847',
    naics_code: '522298',
    industry: 'Invoice Factoring / Trade Finance',
    business_purpose: 'Accounts receivable factoring for small freight carriers and logistics companies.',
    website_url: 'https://www.harborfreightfactors.com',
    website: 'https://www.harborfreightfactors.com',
    mailing_address_street: '1 SE 3rd Avenue, Suite 2050',
    mailing_address_city: 'Miami',
    mailing_address_state: 'FL',
    mailing_address_postal: '33131',
    mailing_address_country: 'US',
    primaryContactFirstName: 'Carlos',
    primaryContactLastName: 'Dominguez',
    primaryContactEmail: 'c.dominguez@harborfreightfactors.com',
    primaryContactPhone: '+1-305-555-0613',
    primaryContactTitle: 'Managing Director',
    accountTypes: JSON.stringify(['operating']),
    account_type_operating: 1,
    account_type_settlement: 0,
    account_type_reserve: 0,
    requestedServices: JSON.stringify(['ach', 'wire']),
    virtual_accounts_required: 0,
    intended_use: 'Funding factored invoices and collecting from shippers/brokers.',
    source_of_funds: 'Factoring fees, collected receivables, and credit facility from regional bank.',
    monthlyTransactionVolume: 4300000,
    estimated_monthly_dollar_volume: 4300000,
    expected_monthly_transaction_count: 2800,
    average_transaction_amount: 1536,
    expected_average_balance: 950000,
    internationalTransactions: 0,
    countries_customers_located: 'US',
    states_customers_located: 'FL, GA, TX, TN, OH',
    customer_types: 'Owner-operator truckers, small freight carriers',
    high_risk_jurisdictions: 0,
    sanctioned_countries_involvement: 0,
    ofac_screening_responsibility: 'Owner performs manual OFAC checks at client onboarding.',
    bsa_aml_attestation: 1,
    compliance_officer_name: 'Carlos Dominguez',
    compliance_officer_contact: 'c.dominguez@harborfreightfactors.com',
    compliance_controls_description: 'Small operation with documented CIP procedures, OFAC checklist at onboarding, and annual compliance review by outside counsel.',
    training_program_available: 0,
    customers_migrating: null,
    transition_plan_available: 0,
    accuracy_attestation: 1,
    electronic_signature: 'Carlos Dominguez',
    signature_date: '2026-02-10',
    monthlyRevenue: 95000,
    employeeCount: 7,
    yearFounded: 2022,
    incorporationState: 'FL',
    form_step_completed: 1,
    status: 'draft',
    assignedTo: '',
    submittedAt: null,
    updatedAt: now,
    notes: 'Application started but not yet submitted. Follow up with client.',
  },
];

// ── Insert applications ────────────────────────────────────────────────────────
const insertApp = db.prepare(`
  INSERT INTO applications (
    id, companyName, legalName, trade_name, businessType, entity_type,
    ein, country_of_incorporation, state_of_incorporation, date_of_incorporation,
    business_registration_number, naics_code, industry, business_purpose,
    website_url, website,
    mailing_address_street, mailing_address_city, mailing_address_state,
    mailing_address_postal, mailing_address_country,
    primaryContactFirstName, primaryContactLastName, primaryContactEmail,
    primaryContactPhone, primaryContactTitle,
    accountTypes, account_type_operating, account_type_settlement, account_type_reserve,
    requestedServices, virtual_accounts_required,
    intended_use, source_of_funds,
    monthlyTransactionVolume, estimated_monthly_dollar_volume,
    expected_monthly_transaction_count, average_transaction_amount,
    expected_average_balance,
    internationalTransactions,
    countries_customers_located, states_customers_located, customer_types,
    high_risk_jurisdictions, sanctioned_countries_involvement,
    ofac_screening_responsibility, bsa_aml_attestation,
    compliance_officer_name, compliance_officer_contact,
    compliance_controls_description, training_program_available,
    customers_migrating, transition_plan_available,
    accuracy_attestation, electronic_signature, signature_date,
    monthlyRevenue, employeeCount, yearFounded, incorporationState,
    form_step_completed, status, assignedTo, submittedAt, updatedAt, notes
  ) VALUES (
    @id, @companyName, @legalName, @trade_name, @businessType, @entity_type,
    @ein, @country_of_incorporation, @state_of_incorporation, @date_of_incorporation,
    @business_registration_number, @naics_code, @industry, @business_purpose,
    @website_url, @website,
    @mailing_address_street, @mailing_address_city, @mailing_address_state,
    @mailing_address_postal, @mailing_address_country,
    @primaryContactFirstName, @primaryContactLastName, @primaryContactEmail,
    @primaryContactPhone, @primaryContactTitle,
    @accountTypes, @account_type_operating, @account_type_settlement, @account_type_reserve,
    @requestedServices, @virtual_accounts_required,
    @intended_use, @source_of_funds,
    @monthlyTransactionVolume, @estimated_monthly_dollar_volume,
    @expected_monthly_transaction_count, @average_transaction_amount,
    @expected_average_balance,
    @internationalTransactions,
    @countries_customers_located, @states_customers_located, @customer_types,
    @high_risk_jurisdictions, @sanctioned_countries_involvement,
    @ofac_screening_responsibility, @bsa_aml_attestation,
    @compliance_officer_name, @compliance_officer_contact,
    @compliance_controls_description, @training_program_available,
    @customers_migrating, @transition_plan_available,
    @accuracy_attestation, @electronic_signature, @signature_date,
    @monthlyRevenue, @employeeCount, @yearFounded, @incorporationState,
    @form_step_completed, @status, @assignedTo, @submittedAt, @updatedAt, @notes
  )
`);

db.transaction(() => {
  for (const app of applications) {
    insertApp.run(app);
  }
})();

console.log(`Inserted ${applications.length} seed applications.`);

// ── Authorized signers for SEED-001 ───────────────────────────────────────────
const insertSigner = db.prepare(`
  INSERT INTO authorized_signers (
    application_id, full_legal_name, title_role, date_of_birth,
    email, phone, gov_id_type, gov_id_number, id_issuing_country, signature_authority
  ) VALUES (
    @application_id, @full_legal_name, @title_role, @date_of_birth,
    @email, @phone, @gov_id_type, @gov_id_number, @id_issuing_country, @signature_authority
  )
`);

db.transaction(() => {
  insertSigner.run({
    application_id: 'SEED-001',
    full_legal_name: 'Rachel Okonkwo',
    title_role: 'Chief Financial Officer',
    date_of_birth: '1982-06-14',
    email: 'r.okonkwo@meridianpay.io',
    phone: '+1-212-555-0182',
    gov_id_type: 'Passport',
    gov_id_number: 'US-A9284710',
    id_issuing_country: 'US',
    signature_authority: 1,
  });

  insertSigner.run({
    application_id: 'SEED-001',
    full_legal_name: 'James T. Prentice',
    title_role: 'Chief Executive Officer',
    date_of_birth: '1978-11-30',
    email: 'j.prentice@meridianpay.io',
    phone: '+1-212-555-0199',
    gov_id_type: "Driver's License",
    gov_id_number: 'NY-D4729183',
    id_issuing_country: 'US',
    signature_authority: 1,
  });
})();

console.log('Inserted 2 authorized signers for SEED-001.');

// ── Ownership / control person for SEED-001 ───────────────────────────────────
const insertOwner = db.prepare(`
  INSERT INTO ownership_control_persons (
    application_id, full_legal_name, ownership_percentage, role,
    date_of_birth, residential_address, gov_id_type, gov_id_number,
    attestation_of_accuracy
  ) VALUES (
    @application_id, @full_legal_name, @ownership_percentage, @role,
    @date_of_birth, @residential_address, @gov_id_type, @gov_id_number,
    @attestation_of_accuracy
  )
`);

insertOwner.run({
  application_id: 'SEED-001',
  full_legal_name: 'James T. Prentice',
  ownership_percentage: 62.5,
  role: 'Founder & Chief Executive Officer',
  date_of_birth: '1978-11-30',
  residential_address: '420 Park Avenue, Apt 18C, New York, NY 10022',
  gov_id_type: "Driver's License",
  gov_id_number: 'NY-D4729183',
  attestation_of_accuracy: 1,
});

console.log('Inserted 1 ownership/control person for SEED-001.');
console.log('\nSeed complete.');

db.close();
